server:
  port: 8080

spring:
  datasource:
    name: springBoot
    url: jdbc:mysql://127.0.0.1:3306/springBoot
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
